# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  container.autowiring.strict_mode: true
#    parameter_name: value

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AppBundle\:
    resource: '../../src/AppBundle/*'

  AppBundle\DataFixtures\:
    resource: '../../src/AppBundle/DataFixtures'
    tags: [ 'doctrine.fixture.orm' ]