name: Composer & Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with pre-release PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Validate composer.json and composer.lock
        run: composer validate -vv

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Yarn install
        run: yarn install

      - name: Yarn build
        run: yarn run encore dev

      - name: set database data
        run: |
          php bin/console doctrine:schema:update --force
          php bin/console doctrine:fixtures:load --no-interaction

      - name: Run code quality checks
        run: vendor/bin/grumphp run --testsuite=code_quality

      - name: Run test suite
        run: vendor/bin/phpunit

    env:
      DATABASE_URL: mysql://root:root@127.0.0.1:3306/test_db
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
